# Generated by Django 4.2 on 2023-05-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('reg_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=255)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
            ],
        ),
    ]
