# Generated by Django 4.2 on 2023-05-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subject_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('attendance', models.PositiveIntegerField()),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
