# Generated by Django 4.2 on 2023-05-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gradeattendance_select_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeattendance',
            name='subject',
        ),
        migrations.AlterField(
            model_name='gradeattendance',
            name='select_subject',
            field=models.CharField(choices=[('Data Structures', 'Data Structures'), ('Object Oriented Programming', 'Object Oriented Programming'), ('Digital Systems Design', 'Digital Systems Design'), ('Design and Analysis of Algorithms', 'Design and Analysis of Algorithms'), ('Formal Languages and Automata Theory', 'Formal Languages and Automata Theory'), ('Operating Systems', 'Operating Systems'), ('Computer Networks', 'Computer Networks'), ('Software Engineering', 'Software Engineering'), ('Compiler Design', 'Compiler Design')], max_length=200),
        ),
    ]
