# Generated by Django 4.2 on 2023-05-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_gradeattendance_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='contact',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='father_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='mother_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
