# Generated by Django 4.2 on 2023-05-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_registration_city_registration_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mother_name',
        ),
    ]
