# Generated by Django 4.2 on 2023-05-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('reg_no', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
